name: Deploy Firebase Functions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./functions
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install Firebase Tools
        run: npm install -g firebase-tools
          
      - name: Install Dependencies
        run: npm ci --legacy-peer-deps
        
      - name: Build
        run: npm run build
        
      - name: Create Production Environment File
        run: |
          echo "# Email Konfiguration" > .env.production
          echo "EMAIL_USER=${{ secrets.EMAIL_USER }}" >> .env.production
          echo "EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}" >> .env.production
          echo "EMAIL_NAME=${{ secrets.EMAIL_NAME }}" >> .env.production
          echo "" >> .env.production
          echo "# Stripe Konfiguration" >> .env.production
          echo "STRIPE_SECRET_KEY=${{ secrets.STRIPE_SECRET_KEY }}" >> .env.production
          echo "STRIPE_WEBHOOK_SECRET=${{ secrets.STRIPE_WEBHOOK_SECRET }}" >> .env.production
          echo "" >> .env.production
          echo "# API URL" >> .env.production
          echo "API_URL=${{ secrets.API_URL }}" >> .env.production
        
      - name: Copy Production Environment
        run: cp .env.production .env
        
      - name: Deploy to Firebase
        run: firebase deploy --only functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          NODE_ENV: production
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_NAME: ${{ secrets.EMAIL_NAME }}
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
          STRIPE_WEBHOOK_SECRET: ${{ secrets.STRIPE_WEBHOOK_SECRET }} 