name: Deploy Firebase Functions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./functions
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install Dependencies
        run: npm ci --legacy-peer-deps
        
      - name: Build
        run: npm run build
        
      - name: Create Production Environment File
        run: |
          echo "# Email Konfiguration" > .env.production
          echo "EMAIL_USER=${{ secrets.EMAIL_USER }}" >> .env.production
          echo "EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}" >> .env.production
          echo "EMAIL_NAME=${{ secrets.EMAIL_NAME }}" >> .env.production
          echo "" >> .env.production
          echo "# Stripe Konfiguration" >> .env.production
          echo "STRIPE_SECRET_KEY=${{ secrets.STRIPE_SECRET_KEY }}" >> .env.production
          echo "STRIPE_WEBHOOK_SECRET=${{ secrets.STRIPE_WEBHOOK_SECRET }}" >> .env.production
          echo "" >> .env.production
          echo "# API URL" >> .env.production
          echo "API_URL=${{ secrets.API_URL }}" >> .env.production
        
      - name: Copy Production Environment
        run: cp .env.production .env

      - name: GitHub Action for Firebase
        uses: w9jds/firebase-action@master
        with:
          args: functions:deploy
        env:
          GCP_SA_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          PROJECT_ID: horizonnet-ed13d
          NODE_ENV: production 